sudo: required
dist: trusty
language: node_js
node_js:
  - "10.4.0"
cache:
  directories: node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # Install Google Chrome:
  # https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
  # http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Install the latest version of Yarn:
  # https://github.com/travis-ci/travis-ci/issues/7566
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - npm run lint
  - npm test
  - npm run build
